// Generated by CoffeeScript 1.3.3
(function() {

  describe('Rogue', function() {
    return it('should exist on the global object', function() {
      return expect(window.Rogue).toBeDefined();
    });
  });

}).call(this);
