// Generated by CoffeeScript 1.3.3
(function() {

  Rogue.ready(function() {
    var app;
    app = {};
    app.game = new Rogue.Game({
      fps: true
    });
    app.input = new Rogue.KeyboardManager(app.game.canvas);
    app.mouse = new Rogue.Mouse(app.game);
    app.state = {
      setup: function() {
        var assets, x, _i, _ref;
        assets = app.assets.core;
        console.log("setup run");
        app.viewport = new Rogue.ViewPort({
          parent: app.game,
          viewWidth: 1000,
          viewHeight: 400
        });
        app.bg1 = new Rogue.Entity({
          image: assets.bg1,
          speed: 0.5,
          repeatX: true,
          require: ["layer"]
        });
        app.bg2 = new Rogue.Entity({
          image: assets.bg2,
          speed: 0.9,
          repeatX: true,
          require: ["layer", "collide", "hitmap"]
        });
        app.player = new Rogue.Entity({
          parent: app.game,
          image: assets.blue,
          require: ["move", "collide", "AABB", "gravity", "tween"],
          onHit: function(col) {
            if (col.dir === "bottom") {
              return this.canJump = true;
            }
          }
        });
        app.tiles = new Rogue.TileMap({
          y: 300,
          size: [30, 1]
        });
        app.viewport.add([app.bg2, app.bg1, app.player, app.tiles]);
        app.viewport.updates[98] = function() {
          this.follow(app.player);
          return this.forceInside(app.player, false);
        };
        app.blocks = [];
        for (x = _i = 0, _ref = app.tiles.size[0]; 0 <= _ref ? _i < _ref : _i > _ref; x = 0 <= _ref ? ++_i : --_i) {
          app.blocks.push(new Rogue.Entity({
            image: assets.red,
            x: x,
            y: 0,
            require: ["sprite", "collide", "AABB"]
          }));
        }
        return app.tiles.place(app.blocks);
      },
      update: function() {
        if (app.input.pressed("right")) {
          app.player.move(2, 0);
        }
        if (app.input.pressed("left")) {
          app.player.move(-2, 0);
        }
        if (app.input.pressed("up")) {
          app.assets.core.jump.play();
          app.player.canJump = false;
          app.player.dy = 17;
        }
        if (app.input.pressed("down")) {
          app.player.move(0, 2);
        }
        return app.viewport.update();
      },
      draw: function() {
        app.game.clear();
        return app.viewport.draw();
      }
    };
    app.assets = new Rogue.AssetManager({
      baseUrl: "",
      packs: {
        core: [
          {
            name: "bg1",
            src: "img/b1.png"
          }, {
            name: "bg2",
            src: "img/b2.png"
          }, {
            name: "red",
            src: "img/1.png"
          }, {
            name: "blue",
            src: "img/2.png"
          }, {
            name: "jump",
            src: "sound/jump.ogg",
            alt: "sound/jump.mp3"
          }
        ]
      },
      preload: false
    });
    app.assets.on("load", "core", function(asset, percent) {
      return console.log("Assets loading: " + percent);
    });
    app.assets.on("complete", "core", function() {
      console.log("Assets loaded");
      return app.game.start(app.state);
    });
    app.assets.download("core");
    return window.app = app;
  });

}).call(this);
